name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: |
            .github/
            node_modules/
            .env*
            *.md
            deploy-*.sh
            render.yaml
            production-*.sql
            production-*.txt

  notify-deployment:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - name: Deployment Complete
        run: |
          echo "🚀 Frontend deployed to GitHub Pages"
          echo "🌐 URL: https://jeremyeletto.github.io/AIHomeSearch/"
          echo ""
          echo "📋 Next steps:"
          echo "1. Deploy backend to Render: https://dashboard.render.com"
          echo "2. Connect GitHub repository to Render"
          echo "3. Set environment variables in Render"
          echo "4. Configure Supabase for production"
          echo ""
          echo "✅ Automated deployment complete!"
